##########################################################################
# 部署配置文件(base)
# 本配置文件(xx.yml)中的变量(${xxx})是从同级目录下的.env文件中读取的
##########################################################################
# compose支持的版本2
version: "2"
services:
  # mongodb
  mongodb:
    image: "${IMAGE_MONGODB}"
    container_name: "mongodb.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "mongodb.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    env_file:
      - ./mongodb.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./volume/mongodb/conf/mongod.conf:/etc/mongo/mongod.conf:ro
      - ./volume/mongodb/data:/data/db:rw
      - ./volume/mongodb/logs:/var/log/mongodb:rw
    command: "--config /etc/mongo/mongod.conf --bind_ip 0.0.0.0 --port 27017"
    network_mode: "host"
    extra_hosts:
      - "mongodb.${PRODUCT_NAME}.${COMPANY_NAME}:${HOST_IP}"
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN
  # express
  express:
    image: "${IMAGE_EXPRESS}"
    container_name: "express.${PRODUCT_NAME}.${COMPANY_NAME}"
    hostname: "express.${PRODUCT_NAME}.${COMPANY_NAME}"
    restart: "always"
    env_file:
      - ./express.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    extra_hosts:
      - "express.${PRODUCT_NAME}.${COMPANY_NAME}:${HOST_IP}"
    # cap_add:
    #   - NET_ADMIN
    #   - SYS_ADMIN
